networks:
  DFEC:
    driver: bridge
services:
  products-server:
    extends:
      file: ./docker-compose.common.yaml
      service: products
    container_name: products-server
    working_dir: /app/products-server
    ports:
      - '8080:8080'
    command: npm run start:dev
    depends_on:
      - products-database
    environment:
      DB_NAME: products
      DB_HOST: products-database
      DB_USER: products-user
      DB_PASSWORD: secret-password
      DB_PORT: 3306
      REDIS_HOST: DFEC-cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: "&2@9J*4h%7F#d16s5V$"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 2m
      timeout: 30s
      retries: 3
    volumes: 
      - ./src/migrations:/app/src/migrations
  products-database:
    image: mysql:8.0.33
    container_name: products-database
    networks: 
      - DFEC
    ports:
      - '3306:3306'
    volumes:
      - products-db:/var/lib/mysql #this will store data inside docker-engine's volume.
    environment:
      MYSQL_ROOT_PASSWORD: Q38t2F5Y#4d
      MYSQL_DATABASE: products
      MYSQL_USER: products-user
      MYSQL_PASSWORD: secret-password
    healthcheck:
      test:
        [
          'CMD',
          'CMD',
          'mysql',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p',
          'Q38t2F5Y#4d',
          '-e',
          'SELECT 1',
        ]
      interval: 1m
      timeout: 10s
      retries: 3
  DFEC-cache:
    #this will later be used at all other services.
    image: redis:7.4.0-alpine
    networks: 
      - DFEC
    container_name: DFEC-redis
    command: redis-server --requirepass "&2@9J*4h%7F#d16s5V$"
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
    # healthcheck:
    #   test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
volumes:
  products-db:
  cache:
