services: 
  products: 
    networks: 
      - DFEC
    image: node:22-alpine
    working_dir: /app
    volumes: 
     - ./:/app
    # healthcheck:
    # deploy:
    environment:
      NODE_ENV: development
      NODE_OPTIONS: '--max-old-space-size=512'
