apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfec-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfec-products 
  template:
    metadata:
      labels:
        app: dfec-products 
    spec:
      containers:
      - name: dfec-products-container
        image: khalidhossain/dfec-products:latest
        envFrom: 
        - configMapRef: 
            name: common-env
        - configMapRef: 
            name: dfec-products-env
        - secretRef:
            name: dfec-secrets
        command: ["npm", "run", "start:prod"]

        livenessProbe: 
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        
        ports:
        - containerPort: 8080 

        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dfec-products-svc
spec: 
  selector:
    app: dfec-products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31110
  type: LoadBalancer