apiVersion: v1
kind: Secret
metadata:
  name: dfec-secrets
  namespace: default
type: Opaque
data: 
  MYSQL_ROOT_PASSWORD: YzJWamNtVjBMWEJoYzNOM2Iz
  DB_PASSWORD: YzJWamNtVjBMWEJoYzNOM2Iz
  REDIS_PASSWORD: JjJAOUoqNGglN0YjZDE2czVWJA==
# c2VjcmV0LXBhc3N3b3