apiVersion: v1
kind: Secret
metadata:
  name: dfec-products-secrets
  namespace: default
type: Opaque
data: 
  REDIS_PASSWORD: JjJAOUoqNGglN0YjZDE2czVWJA== #'&2@9J*4h%7F#d16s5V$'
  DB_PASSWORD: c2VjcmV0LXBhc3N3b3Jk #secret-password